// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backup.proto

package com.distribute.grpc;

/**
 * Protobuf service {@code BackupService}
 */
public  abstract class BackupService
    implements com.google.protobuf.Service {
  protected BackupService() {}

  public interface Interface {
    /**
     * <code>rpc pull(.TransferRequest) returns (.TransferStatus);</code>
     */
    public abstract void pull(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done);

    /**
     * <code>rpc push(.TransferResponse) returns (.TransferRequest);</code>
     */
    public abstract void push(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferResponse request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.TransferRequest> done);

    /**
     * <code>rpc delete(.TransferRequest) returns (.TransferStatus);</code>
     */
    public abstract void delete(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new BackupService() {
      @java.lang.Override
      public  void pull(
          com.google.protobuf.RpcController controller,
          com.distribute.grpc.TransferRequest request,
          com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done) {
        impl.pull(controller, request, done);
      }

      @java.lang.Override
      public  void push(
          com.google.protobuf.RpcController controller,
          com.distribute.grpc.TransferResponse request,
          com.google.protobuf.RpcCallback<com.distribute.grpc.TransferRequest> done) {
        impl.push(controller, request, done);
      }

      @java.lang.Override
      public  void delete(
          com.google.protobuf.RpcController controller,
          com.distribute.grpc.TransferRequest request,
          com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done) {
        impl.delete(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.pull(controller, (com.distribute.grpc.TransferRequest)request);
          case 1:
            return impl.push(controller, (com.distribute.grpc.TransferResponse)request);
          case 2:
            return impl.delete(controller, (com.distribute.grpc.TransferRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.distribute.grpc.TransferRequest.getDefaultInstance();
          case 1:
            return com.distribute.grpc.TransferResponse.getDefaultInstance();
          case 2:
            return com.distribute.grpc.TransferRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.distribute.grpc.TransferStatus.getDefaultInstance();
          case 1:
            return com.distribute.grpc.TransferRequest.getDefaultInstance();
          case 2:
            return com.distribute.grpc.TransferStatus.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc pull(.TransferRequest) returns (.TransferStatus);</code>
   */
  public abstract void pull(
      com.google.protobuf.RpcController controller,
      com.distribute.grpc.TransferRequest request,
      com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done);

  /**
   * <code>rpc push(.TransferResponse) returns (.TransferRequest);</code>
   */
  public abstract void push(
      com.google.protobuf.RpcController controller,
      com.distribute.grpc.TransferResponse request,
      com.google.protobuf.RpcCallback<com.distribute.grpc.TransferRequest> done);

  /**
   * <code>rpc delete(.TransferRequest) returns (.TransferStatus);</code>
   */
  public abstract void delete(
      com.google.protobuf.RpcController controller,
      com.distribute.grpc.TransferRequest request,
      com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.distribute.grpc.BackupInt.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.pull(controller, (com.distribute.grpc.TransferRequest)request,
          com.google.protobuf.RpcUtil.<com.distribute.grpc.TransferStatus>specializeCallback(
            done));
        return;
      case 1:
        this.push(controller, (com.distribute.grpc.TransferResponse)request,
          com.google.protobuf.RpcUtil.<com.distribute.grpc.TransferRequest>specializeCallback(
            done));
        return;
      case 2:
        this.delete(controller, (com.distribute.grpc.TransferRequest)request,
          com.google.protobuf.RpcUtil.<com.distribute.grpc.TransferStatus>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.distribute.grpc.TransferRequest.getDefaultInstance();
      case 1:
        return com.distribute.grpc.TransferResponse.getDefaultInstance();
      case 2:
        return com.distribute.grpc.TransferRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.distribute.grpc.TransferStatus.getDefaultInstance();
      case 1:
        return com.distribute.grpc.TransferRequest.getDefaultInstance();
      case 2:
        return com.distribute.grpc.TransferStatus.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.distribute.grpc.BackupService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void pull(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.distribute.grpc.TransferStatus.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.distribute.grpc.TransferStatus.class,
          com.distribute.grpc.TransferStatus.getDefaultInstance()));
    }

    public  void push(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferResponse request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.TransferRequest> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.distribute.grpc.TransferRequest.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.distribute.grpc.TransferRequest.class,
          com.distribute.grpc.TransferRequest.getDefaultInstance()));
    }

    public  void delete(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.TransferStatus> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.distribute.grpc.TransferStatus.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.distribute.grpc.TransferStatus.class,
          com.distribute.grpc.TransferStatus.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.distribute.grpc.TransferStatus pull(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request)
        throws com.google.protobuf.ServiceException;

    public com.distribute.grpc.TransferRequest push(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferResponse request)
        throws com.google.protobuf.ServiceException;

    public com.distribute.grpc.TransferStatus delete(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.distribute.grpc.TransferStatus pull(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.distribute.grpc.TransferStatus) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.distribute.grpc.TransferStatus.getDefaultInstance());
    }


    public com.distribute.grpc.TransferRequest push(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferResponse request)
        throws com.google.protobuf.ServiceException {
      return (com.distribute.grpc.TransferRequest) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.distribute.grpc.TransferRequest.getDefaultInstance());
    }


    public com.distribute.grpc.TransferStatus delete(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.TransferRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.distribute.grpc.TransferStatus) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.distribute.grpc.TransferStatus.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:BackupService)
}

