// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: directory.proto

package com.distribute.grpc;

/**
 * Protobuf service {@code DirectoryService}
 */
public  abstract class DirectoryService
    implements com.google.protobuf.Service {
  protected DirectoryService() {}

  public interface Interface {
    /**
     * <code>rpc Ls(.LsRequest) returns (.LsResponse);</code>
     */
    public abstract void ls(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.LsResponse> done);

    /**
     * <code>rpc mkdir(.LsRequest) returns (.MkdirResponse);</code>
     */
    public abstract void mkdir(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done);

    /**
     * <code>rpc cd(.LsRequest) returns (.MkdirResponse);</code>
     */
    public abstract void cd(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new DirectoryService() {
      @java.lang.Override
      public  void ls(
          com.google.protobuf.RpcController controller,
          com.distribute.grpc.LsRequest request,
          com.google.protobuf.RpcCallback<com.distribute.grpc.LsResponse> done) {
        impl.ls(controller, request, done);
      }

      @java.lang.Override
      public  void mkdir(
          com.google.protobuf.RpcController controller,
          com.distribute.grpc.LsRequest request,
          com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done) {
        impl.mkdir(controller, request, done);
      }

      @java.lang.Override
      public  void cd(
          com.google.protobuf.RpcController controller,
          com.distribute.grpc.LsRequest request,
          com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done) {
        impl.cd(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.ls(controller, (com.distribute.grpc.LsRequest)request);
          case 1:
            return impl.mkdir(controller, (com.distribute.grpc.LsRequest)request);
          case 2:
            return impl.cd(controller, (com.distribute.grpc.LsRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.distribute.grpc.LsRequest.getDefaultInstance();
          case 1:
            return com.distribute.grpc.LsRequest.getDefaultInstance();
          case 2:
            return com.distribute.grpc.LsRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.distribute.grpc.LsResponse.getDefaultInstance();
          case 1:
            return com.distribute.grpc.MkdirResponse.getDefaultInstance();
          case 2:
            return com.distribute.grpc.MkdirResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc Ls(.LsRequest) returns (.LsResponse);</code>
   */
  public abstract void ls(
      com.google.protobuf.RpcController controller,
      com.distribute.grpc.LsRequest request,
      com.google.protobuf.RpcCallback<com.distribute.grpc.LsResponse> done);

  /**
   * <code>rpc mkdir(.LsRequest) returns (.MkdirResponse);</code>
   */
  public abstract void mkdir(
      com.google.protobuf.RpcController controller,
      com.distribute.grpc.LsRequest request,
      com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done);

  /**
   * <code>rpc cd(.LsRequest) returns (.MkdirResponse);</code>
   */
  public abstract void cd(
      com.google.protobuf.RpcController controller,
      com.distribute.grpc.LsRequest request,
      com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.distribute.grpc.DirectoryInt.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.ls(controller, (com.distribute.grpc.LsRequest)request,
          com.google.protobuf.RpcUtil.<com.distribute.grpc.LsResponse>specializeCallback(
            done));
        return;
      case 1:
        this.mkdir(controller, (com.distribute.grpc.LsRequest)request,
          com.google.protobuf.RpcUtil.<com.distribute.grpc.MkdirResponse>specializeCallback(
            done));
        return;
      case 2:
        this.cd(controller, (com.distribute.grpc.LsRequest)request,
          com.google.protobuf.RpcUtil.<com.distribute.grpc.MkdirResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.distribute.grpc.LsRequest.getDefaultInstance();
      case 1:
        return com.distribute.grpc.LsRequest.getDefaultInstance();
      case 2:
        return com.distribute.grpc.LsRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.distribute.grpc.LsResponse.getDefaultInstance();
      case 1:
        return com.distribute.grpc.MkdirResponse.getDefaultInstance();
      case 2:
        return com.distribute.grpc.MkdirResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.distribute.grpc.DirectoryService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void ls(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.LsResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.distribute.grpc.LsResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.distribute.grpc.LsResponse.class,
          com.distribute.grpc.LsResponse.getDefaultInstance()));
    }

    public  void mkdir(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.distribute.grpc.MkdirResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.distribute.grpc.MkdirResponse.class,
          com.distribute.grpc.MkdirResponse.getDefaultInstance()));
    }

    public  void cd(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request,
        com.google.protobuf.RpcCallback<com.distribute.grpc.MkdirResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.distribute.grpc.MkdirResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.distribute.grpc.MkdirResponse.class,
          com.distribute.grpc.MkdirResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.distribute.grpc.LsResponse ls(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request)
        throws com.google.protobuf.ServiceException;

    public com.distribute.grpc.MkdirResponse mkdir(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request)
        throws com.google.protobuf.ServiceException;

    public com.distribute.grpc.MkdirResponse cd(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.distribute.grpc.LsResponse ls(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.distribute.grpc.LsResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.distribute.grpc.LsResponse.getDefaultInstance());
    }


    public com.distribute.grpc.MkdirResponse mkdir(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.distribute.grpc.MkdirResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(1),
        controller,
        request,
        com.distribute.grpc.MkdirResponse.getDefaultInstance());
    }


    public com.distribute.grpc.MkdirResponse cd(
        com.google.protobuf.RpcController controller,
        com.distribute.grpc.LsRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.distribute.grpc.MkdirResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(2),
        controller,
        request,
        com.distribute.grpc.MkdirResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:DirectoryService)
}

