// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.distribute.grpc;

public final class fileInt {
  private fileInt() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileRequestBrif_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileRequestBrif_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nfile.proto\"#\n\017FileRequestBrif\022\020\n\010fileN" +
      "ame\030\001 \001(\t\"0\n\013FileRequest\022\020\n\010fileName\030\001 \001" +
      "(\t\022\017\n\007content\030\002 \001(\014\"-\n\014FileResponse\022\017\n\007c" +
      "ontent\030\001 \001(\014\022\014\n\004lock\030\002 \001(\0052\336\001\n\013FileServi" +
      "ce\022%\n\006Upload\022\014.FileRequest\032\r.FileRespons" +
      "e\022+\n\010Download\022\020.FileRequestBrif\032\r.FileRe" +
      "sponse\022%\n\006Update\022\014.FileRequest\032\r.FileRes" +
      "ponse\022)\n\006Delete\022\020.FileRequestBrif\032\r.File" +
      "Response\022)\n\006Commit\022\020.FileRequestBrif\032\r.F" +
      "ileResponseB#\n\023com.distribute.grpcB\007file" +
      "IntP\001\210\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FileRequestBrif_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FileRequestBrif_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileRequestBrif_descriptor,
        new java.lang.String[] { "FileName", });
    internal_static_FileRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_FileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileRequest_descriptor,
        new java.lang.String[] { "FileName", "Content", });
    internal_static_FileResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_FileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FileResponse_descriptor,
        new java.lang.String[] { "Content", "Lock", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
