// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file.proto

package com.distribute.grpc;

public interface FileRequestBrifOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileRequestBrif)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fileName = 1;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string fileName = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
