// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.distribute.grpc;

public interface HelloRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string school = 1;</code>
   * @return The school.
   */
  java.lang.String getSchool();
  /**
   * <code>string school = 1;</code>
   * @return The bytes for school.
   */
  com.google.protobuf.ByteString
      getSchoolBytes();

  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int32 age = 3;</code>
   * @return The age.
   */
  int getAge();
}
