// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.distribute.grpc;

public final class HelloWorldProto {
  private HelloWorldProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HelloResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HelloResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\"(\n\014HelloRequest\022\014\n\004name\030\001 " +
      "\001(\t\022\n\n\002id\030\002 \001(\005\"9\n\tHelloResp\022\016\n\006school\030\001" +
      " \001(\t\022\017\n\007address\030\002 \001(\t\022\013\n\003age\030\003 \001(\00525\n\nHe" +
      "lloWorld\022\'\n\010sayHello\022\r.HelloRequest\032\n.He" +
      "lloResp\"\000B(\n\023com.distribute.grpcB\017HelloW" +
      "orldProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloRequest_descriptor,
        new java.lang.String[] { "Name", "Id", });
    internal_static_HelloResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HelloResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HelloResp_descriptor,
        new java.lang.String[] { "School", "Address", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
