// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.distribute.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 赋值是为了定义这个变量在message中的位置
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * 赋值是为了定义这个变量在message中的位置
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();
}
