// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: directory.proto

package com.distribute.grpc;

public interface LsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string path = 1;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string path = 1;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
