// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: directory.proto

package com.distribute.grpc;

/**
 * Protobuf type {@code LsResponse}
 */
public final class LsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LsResponse)
    LsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LsResponse.newBuilder() to construct.
  private LsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LsResponse() {
    filenames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.distribute.grpc.DirectoryInt.internal_static_LsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.distribute.grpc.DirectoryInt.internal_static_LsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.distribute.grpc.LsResponse.class, com.distribute.grpc.LsResponse.Builder.class);
  }

  public static final int FILENAMES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList filenames_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string filenames = 1;</code>
   * @return A list containing the filenames.
   */
  public com.google.protobuf.ProtocolStringList
      getFilenamesList() {
    return filenames_;
  }
  /**
   * <code>repeated string filenames = 1;</code>
   * @return The count of filenames.
   */
  public int getFilenamesCount() {
    return filenames_.size();
  }
  /**
   * <code>repeated string filenames = 1;</code>
   * @param index The index of the element to return.
   * @return The filenames at the given index.
   */
  public java.lang.String getFilenames(int index) {
    return filenames_.get(index);
  }
  /**
   * <code>repeated string filenames = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the filenames at the given index.
   */
  public com.google.protobuf.ByteString
      getFilenamesBytes(int index) {
    return filenames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < filenames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filenames_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < filenames_.size(); i++) {
        dataSize += computeStringSizeNoTag(filenames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getFilenamesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.distribute.grpc.LsResponse)) {
      return super.equals(obj);
    }
    com.distribute.grpc.LsResponse other = (com.distribute.grpc.LsResponse) obj;

    if (!getFilenamesList()
        .equals(other.getFilenamesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFilenamesCount() > 0) {
      hash = (37 * hash) + FILENAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFilenamesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.distribute.grpc.LsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distribute.grpc.LsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distribute.grpc.LsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distribute.grpc.LsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distribute.grpc.LsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.distribute.grpc.LsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.distribute.grpc.LsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distribute.grpc.LsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.distribute.grpc.LsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.distribute.grpc.LsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.distribute.grpc.LsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.distribute.grpc.LsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.distribute.grpc.LsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code LsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LsResponse)
      com.distribute.grpc.LsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.distribute.grpc.DirectoryInt.internal_static_LsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.distribute.grpc.DirectoryInt.internal_static_LsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.distribute.grpc.LsResponse.class, com.distribute.grpc.LsResponse.Builder.class);
    }

    // Construct using com.distribute.grpc.LsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      filenames_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.distribute.grpc.DirectoryInt.internal_static_LsResponse_descriptor;
    }

    @java.lang.Override
    public com.distribute.grpc.LsResponse getDefaultInstanceForType() {
      return com.distribute.grpc.LsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.distribute.grpc.LsResponse build() {
      com.distribute.grpc.LsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.distribute.grpc.LsResponse buildPartial() {
      com.distribute.grpc.LsResponse result = new com.distribute.grpc.LsResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.distribute.grpc.LsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        filenames_.makeImmutable();
        result.filenames_ = filenames_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.distribute.grpc.LsResponse) {
        return mergeFrom((com.distribute.grpc.LsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.distribute.grpc.LsResponse other) {
      if (other == com.distribute.grpc.LsResponse.getDefaultInstance()) return this;
      if (!other.filenames_.isEmpty()) {
        if (filenames_.isEmpty()) {
          filenames_ = other.filenames_;
          bitField0_ |= 0x00000001;
        } else {
          ensureFilenamesIsMutable();
          filenames_.addAll(other.filenames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureFilenamesIsMutable();
              filenames_.add(s);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList filenames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureFilenamesIsMutable() {
      if (!filenames_.isModifiable()) {
        filenames_ = new com.google.protobuf.LazyStringArrayList(filenames_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @return A list containing the filenames.
     */
    public com.google.protobuf.ProtocolStringList
        getFilenamesList() {
      filenames_.makeImmutable();
      return filenames_;
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @return The count of filenames.
     */
    public int getFilenamesCount() {
      return filenames_.size();
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @param index The index of the element to return.
     * @return The filenames at the given index.
     */
    public java.lang.String getFilenames(int index) {
      return filenames_.get(index);
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the filenames at the given index.
     */
    public com.google.protobuf.ByteString
        getFilenamesBytes(int index) {
      return filenames_.getByteString(index);
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @param index The index to set the value at.
     * @param value The filenames to set.
     * @return This builder for chaining.
     */
    public Builder setFilenames(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilenamesIsMutable();
      filenames_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @param value The filenames to add.
     * @return This builder for chaining.
     */
    public Builder addFilenames(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureFilenamesIsMutable();
      filenames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @param values The filenames to add.
     * @return This builder for chaining.
     */
    public Builder addAllFilenames(
        java.lang.Iterable<java.lang.String> values) {
      ensureFilenamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, filenames_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilenames() {
      filenames_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string filenames = 1;</code>
     * @param value The bytes of the filenames to add.
     * @return This builder for chaining.
     */
    public Builder addFilenamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureFilenamesIsMutable();
      filenames_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LsResponse)
  }

  // @@protoc_insertion_point(class_scope:LsResponse)
  private static final com.distribute.grpc.LsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.distribute.grpc.LsResponse();
  }

  public static com.distribute.grpc.LsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LsResponse>
      PARSER = new com.google.protobuf.AbstractParser<LsResponse>() {
    @java.lang.Override
    public LsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.distribute.grpc.LsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

