// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: backup.proto

package com.distribute.grpc;

public interface TransferStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransferStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();
}
